# Generated by Django 2.2.5 on 2020-05-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20200507_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='MovieHasDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Movies.Director')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Movies.Movie')),
            ],
            options={
                'db_table': 'movie_has_director',
            },
        ),
    ]
