# Generated by Django 2.2.5 on 2020-05-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_actor_movierolerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierolerating',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
