# Generated by Django 2.2.5 on 2020-05-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0005_auto_20200508_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='votes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='RoleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
                ('movie_role_rating', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Movies.RoleComment')),
            ],
            options={
                'db_table': 'role_comment',
            },
        ),
    ]
