# Generated by Django 2.2.5 on 2020-05-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_auto_20200519_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolecomment',
            name='movie_role_rating',
        ),
        migrations.DeleteModel(
            name='MovieRoleRating',
        ),
        migrations.DeleteModel(
            name='RoleComment',
        ),
    ]
