# Generated by Django 2.2.5 on 2020-05-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0008_movierole'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=2, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('movie_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Movies.MovieRole')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Movies.RoleComment')),
            ],
            options={
                'db_table': 'role_comment',
            },
        ),
    ]
