# Generated by Django 2.2.5 on 2020-05-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0009_rolecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0, max_length=2, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('movie_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Movies.MovieRole')),
            ],
            options={
                'db_table': 'role_level',
            },
        ),
    ]
