# Generated by Django 2.2.5 on 2020-05-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0010_rolelevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolelevel',
            name='level',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
