# Generated by Django 2.2.5 on 2020-05-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0011_auto_20200520_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255, null=True)),
                ('composer', models.CharField(max_length=255, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=2, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Movies.Movie')),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
