# Generated by Django 2.2.5 on 2020-05-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0012_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierole',
            name='level',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='RoleLevel',
        ),
    ]
