# Generated by Django 2.2.5 on 2020-05-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0015_moviemusic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='composer',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
